#数据库的配置信息
SECRET_KEY="123456"


HOSTNAME="127.0.0.1"
DATABASE="wechat"
USERNAME="root"
PASSWORD="Mjy123456~"
DB_URI="mysql+pymysql://{}:{}@{}/{}?charset=utf8".format(USERNAME,PASSWORD,HOSTNAME,DATABASE)
SQLALCHEMY_DATABASE_URI=DB_URI


MAIL_SERVER = 'smtp.163.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'm626164783@163.com'
MAIL_PASSWORD = 'XTYZNRMJLLCIYRUJ'